### ISSUE TITLE
No module named Fcheck

### ISSUE THREAD

**Issue by guinslym** [ubc-library-rc/fcheck#1]
I am getting this error after installing it on Windows. I intalled it on a virtualenv using python 3.9.2

![image](https://user-images.githubusercontent.com/4588993/120524864-85fe7c80-c3a5-11eb-8f6e-487eb5d6a70e.png)

**Comment by plesubc** [comment]
That's . . . odd. Just to double check, did you follow this procedure?
0. git clone https://github.com/ubc-library-rc/fcheck
1. create your virtual env (ie, python -m venv [dir])
2. start it (in the case of Windows, I believe it's Scripts/bin/activate
3. change directory to fcheck
4. pip install .

while your virtual env is active, what is the output of `pip list`?

It should look something like this:
Package         Version
--------------- -------
fcheck          0.1.0
numpy           1.20.3
pandas          1.2.4
pip             18.1
pyreadstat      1.1.2
python-dateutil 2.8.1
pytz            2021.1
setuptools      40.6.2
six             1.16.0

**Comment by plesubc** [comment]
I've done some more investigating of this issue. If you have multiple Python installations, Windows is not tremendously good at separating them out. For instance, on my test machine, even with my preferred Python at the head of my %PATH%, Windows will run any python application (ie, with any extension .py) with the antiquated Python 2.7 which is installed because of my use of ArcGIS.

One possible fix (which could damage the functionality of ArcGIS) is to edit the registry key at Computer\HKEY_CLASSES_ROOT\Python.File\shell\open\command. Note that this key may have a value even if you don't have ArcGIS installed. Also, if you're using venv, if you point it to your normal Python executable, it may still fail.

The simple but irritating solution when using venv is to call it explicitly with Python: ie, python /path/to/damage.py.

The very easiest solution is to just download the binary file and use it instead; it should be completely self contained.

**Comment by plesubc** [comment]
I have managed to track the error down; the module should now function properly in your venv.  Please pull or update with pop. I apologize for the delay in repairing it. If you still have issues (and with my luck, I will have introduced another typo), please open another ticket.

**Comment by plesubc** [comment]
I have discovered one further error which can affect installation on Windows, which requires the insertion of `#!python` on line 1 of damage.py
